language: node_js
node_js: 10
addons:
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
  firefox: "53.0"
  postgresql: "9.6"
  sauce_connect: true
services:
  - postgresql
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - ./public/firefox-allow-popups.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g greenkeeper-lockfile@1
install:
  - npm ci
before_script:
  - npm run start:ci &
  - sleep 2
before_test: greenkeeper-lockfile-update
after_test: greenkeeper-lockfile-upload
script: npm run test:ci
