name: CI
on: push
jobs:

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [12.x]
    services:
      postgres:
        image: postgis/postgis:9.6-2.5
        env:
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
          scVersion: 4.6.4
      - run: npm ci
      - run: npm run test:common
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/lbh3_test
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
      - run: node public/test.sauce-labs.js
        env:
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

  lighthouse:
    runs-on: ubuntu-22.04
    needs: test
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run review-app test
        id: review_app_test  # `id` value is used to refer the outputs from the corresponding action
        uses: LBH3/reviewapps-deploy-status@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Max time to be spent retrying for the build check, default is 120
          deployments_timeout: 480

          # Max time to be spent retrying for the response check, default is 120
          publish_timeout: 480

      # `steps.review_app_test.outputs.review_app_url` must be used in workflow to fetch the Review App URL
      - name: Check review_app_url
        run: |
          echo "Outputs - ${{ steps.review_app_test.outputs.review_app_url }}"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: ./.lighthouserc.json
          runs: 5
          temporaryPublicStorage: true
          urls: |
            ${{ steps.review_app_test.outputs.review_app_url }}
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files
